In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

# Step 1: Load first 50,000 rows
df = pd.read_csv("Reviews.csv", nrows=50000)

# Step 2: Select three sentences containing "light"
sentences = [
    "This olive oil is wonderful and very light on the stomach.",
    "The packaging was broken and let too much light inside the box.",
    "I prefer this brand because it is a light and healthy snack."
]

# Step 3: Vectorization
vectorizer = CountVectorizer()

doc_term_matrix = vectorizer.fit_transform(sentences)

dense_matrix = doc_term_matrix.toarray()

print("Vocabulary:")
print(vectorizer.get_feature_names_out())

print("\nDense Matrix:")
print(dense_matrix)

# Step 4: Vector Slicing
vec_1 = dense_matrix[0]
vec_2 = dense_matrix[1]
vec_3 = dense_matrix[2]

# Step 5: Dot Product Similarity
similarity_1_2 = np.dot(vec_1, vec_2)
similarity_1_3 = np.dot(vec_1, vec_3)

# Step 6: Console Output
print("\nSimilarity Scores")
print("-----------------")
print("Sentence 1 vs Sentence 2:", similarity_1_2)
print("Sentence 1 vs Sentence 3:", similarity_1_3)


Vocabulary:
['and' 'because' 'box' 'brand' 'broken' 'healthy' 'inside' 'is' 'it' 'let'
 'light' 'much' 'oil' 'olive' 'on' 'packaging' 'prefer' 'snack' 'stomach'
 'the' 'this' 'too' 'very' 'was' 'wonderful']

Dense Matrix:
[[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
 [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]]

Similarity Scores
-----------------
Sentence 1 vs Sentence 2: 4
Sentence 1 vs Sentence 3: 4
